namespace Melodee.Common.Constants;


public static class SettingRegistry
{
    public const string ConversionBitrate = "conversion.bitrate";
    public const string ConversionEnabled = "conversion.enabled";
    public const string ConversionSamplingRate = "conversion.samplingRate";
    public const string ConversionVbrLevel = "conversion.vbrLevel";
    public const string DefaultsPageSize = "defaults.pagesize";
    public const string EncryptionPrivateKey = "encryption.privateKey";
    public const string FilteringLessThanDuration = "filtering.lessThanDuration";
    public const string FilteringLessThanSongCount = "filtering.lessThanSongCount";
    public const string FormattingDateTimeDisplayActivityFormat = "formatting.dateTimeDisplayActivityFormat";
    public const string FormattingDateTimeDisplayFormatShort = "formatting.dateTimeDisplayFormatShort";
    public const string ImagingDoLoadEmbeddedImages = "processing.doLoadEmbeddedImages";    
    public const string ImagingMaximumNumberOfAlbumImages = "imaging.maximumNumberOfAlbumImages";
    public const string ImagingMaximumNumberOfArtistImages = "imaging.maximumNumberOfArtistImages";
    public const string ImagingMaximumImageSize = "imaging.imagingMaximumImageSize";
    public const string MagicDoRemoveFeaturingArtistFromSongArtist = "magic.doRemoveFeaturingArtistFromSongArtist";
    public const string MagicDoRemoveFeaturingArtistFromSongTitle = "magic.doRemoveFeaturingArtistFromSongTitle";
    public const string MagicDoRemoveUnwantedTextFromAlbumTitle = "magic.doRemoveUnwantedTextFromAlbumTitle";
    public const string MagicDoRemoveUnwantedTextFromSongTitles = "magic.doRemoveUnwantedTextFromSongTitles";
    public const string MagicDoRenumberSongs = "magic.doRenumberSongs";
    public const string MagicDoReplaceSongsArtistSeparators = "magic.doReplaceSongsArtistSeparators";
    public const string MagicDoSetYearToCurrentIfInvalid = "magic.doSetYearToCurrentIfInvalid";
    public const string MagicEnabled = "magic.enabled";
    public const string PluginEnabledCueSheet = "plugin.cueSheet.enabled";
    public const string PluginEnabledNfo = "plugin.nfo.enabled";
    public const string PluginEnabledM3u = "plugin.m3u.enabled";
    public const string PluginEnabledSimpleFileVerification = "plugin.simpleFileVerification.enabled";
    public const string ProcessingAlbumTitleRemovals = "processing.albumTitleRemovals";
    public const string ProcessingArtistNameReplacements = "processing.artistNameReplacements";
    public const string ProcessingBatchSize = "processing.processingBatchSize";
    public const string ProcessingConvertedExtension = "processing.convertedExtension";
    public const string ProcessingDoContinueOnDirectoryProcessingErrors = "processing.doContinueOnDirectoryProcessingErrors";
    public const string ProcessingDoDeleteOriginal = "processing.doDeleteOriginal";
    public const string ProcessingDoOverrideExistingMelodeeDataFiles = "processing.doOverrideExistingMelodeeDataFiles";
    public const string ProcessingDoUseCurrentYearAsDefaultOrigAlbumYearValue = "processing.doUseCurrentYearAsDefaultOrigAlbumYearValue";
    public const string ProcessingIgnoredArticles = "processing.ignoredArticles";
    public const string ProcessingMaximumAlbumDirectoryNameLength = "processing.maximumAlbumDirectoryNameLength";
    public const string ProcessingMaximumArtistDirectoryNameLength = "processing.maximumArtistDirectoryNameLength";
    public const string ProcessingMaximumProcessingCount = "processing.maximumProcessingCount";
    public const string ProcessingProcessedExtension = "processing.processedExtension";
    public const string ProcessingSkippedExtension = "processing.skippedExtension";
    public const string ProcessingSongTitleRemovals = "processing.songTitleRemovals";
    public const string ProcessingStagingDirectoryScanLimit = "processing.stagingDirectoryScanLimit";
    public const string ScriptingEnabled = "scripting.enabled";
    public const string ScriptingPostDiscoveryScript = "scripting.postDiscoveryScript";
    public const string ScriptingPreDiscoveryScript = "scripting.preDiscoveryScript";
    public const string SearchEngineEnabledBingImage = "searchEngine.bingImage.enabled";
    public const string SearchEngineApiKeyBingImage = "searchEngine.bingImage.apiKey";
    public const string SearchEngineUserAgent = "searchEngine.userAgent";
    public const string SearchEngineDefaultPageSize = "searchEngine.defaultPageSize";
    public const string OpenSubsonicServerLicenseEmail = "scripting.openSubsonicServerLicenseEmail";
    public const string OpenSubsonicServerSupportedVersion = "scripting.openSubsonicServerSupportedVersion";
    public const string OpenSubsonicServerType = "scripting.openSubsonicServerType";
    public const string OpenSubsonicServerVersion = "scripting.openSubsonicServerVersion";
    public const string UserInterfaceToastAutoCloseTime = "userinterface.toastAutoCloseTime";
    public const string ValidationMaximumAlbumYear = "validation.maximumAlbumYear";
    public const string ValidationMaximumMediaNumber = "validation.maximumMediaNumber";
    public const string ValidationMaximumSongNumber = "validation.maximumSongNumber";
    public const string ValidationMinimumAlbumYear = "validation.minimumAlbumYear";
}
